#name: Deploy user service
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#
#jobs:
#  build-and-push:
#    runs-on: ubuntu-latest
#    steps:
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USER }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#
#      - name: Build and Push Image
#        run: |
#          docker build -t stannisl/kfd-user-service:latest -f Dockerfile .
#          docker push stannisl/kfd-user-service:latest


name: Deploy user service

on:
  push:
    tags:
      - 'v*'
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: chmod
        run: chmod +x gradlew

      - name: Extract version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and Push
        run: |
          docker build -t stannisl/kfd-user-service:${{ steps.version.outputs.version }} -f Dockerfile .
          docker push stannisl/kfd-user-service:${{ steps.version.outputs.version }}